#Site description
description: "Up to date news and tips for using Hugo and other static site tools"

# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown: true

# Number of tags to be displayed.
tagsLimit: 20

# Dark mode by default : dark
# Light mode by default : light
darkmode: "dark"

# Date format
date_format: "02/01/2006"

post:
  # Show thumbnails
  thumbnail: true

  # Disable the "NO IMAGE" image.
  noimage: true

  # Number of characters in post summary display
  summary: 280

widgets:
  # Display widgets
  display: true

  # Order of widgets to display
  # widgets: ["search", "archive", "category", "tags", "recent"]
  widgets: ["search", "categories", "tags", "recent"]
  # "search", 









  